// import type { Metadata } from "next";
// import "./globals.css";
// import localFont from "next/font/local";
// import NavBar from "./NavBar";


// const GeistSans = localFont({
//   src: "./fonts/GeistSans.woff2",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const GeistMono = localFont({
//   src: "./fonts/GeistMono-Black.woff2",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "My App",
//   description: "Next.js + Prisma + MySQL project",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" data-theme="winter">
//       <body
//         className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
//       >
//         <NavBar />
//         <main className="p-5">{children}</main>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <NavBar />
          <main className="p-5">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
